# Used for booting up redis and postgresql

version: "3.5"

services:
  db:
    image: postgres:11.1-alpine
    restart: unless-stopped
    environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=database
    ports:
    - "5432:5432"
    volumes:
    - postgresql_data:/var/lib/postgresql/dat

  redis:
    image: redis
    ports:
    - "6379:6379"

volumes:
  postgresql_data:
